version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cronuz_postgres
    restart: always
    environment:
      POSTGRES_USER: cronuz_admin
      POSTGRES_PASSWORD: cronuz_password_123
      POSTGRES_DB: cronuz_b2b_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
